# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jiri Stepanek
description: 17yo — czech student living in the USA | marketing, cryptocurrencies, webDev...
keywords: Czech Student,international student,marketing,webdeveloper,crypto,cryptocurrencies,PalmMedia,lanistae,arkun
author: palmmedia.co
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://palmmedia.co" # the base hostname & protocol for your site
permalink: /:title.html

# Build settings
markdown: kramdown
